version: '3.7'
services:
  # =================================
  # Kafka resources
  # =================================
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      #  1 partitions have leader brokers without a matching listener, including [applicationlog-0]
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # https://www.confluent.io/blog/kafka-listeners-explained/
      # listern = kafkaの窓口
      # hostからは9092, docker-composeのcontainer同士からは29092
      # hostからはzookeeper経由でアクセス可能
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:29092
      # clientがzookpeeperから返されるやり取り先
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      # 他brokerからアクセスするときのlistener
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      
  logstash:
    build: ./logstash
    container_name: logstash
    depends_on: 
      - kafka
      - elasticsearch
    ports:
      # for beats to access to logstash
      - 5044:5044
      # for monitoring api. this is used by kibana
      - 9600:9600

  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    build: ./kibana
    container_name: kibana
    depends_on: 
      - elasticsearch
    ports:
      - 5601:5601
